// src/scene/Table.svelte
<script lang="ts">
  import type { Hand } from "../game-state/game-state";
  import {
    Mesh,
    DoubleSide,
    PlaneBufferGeometry,
    Vector3,
    MeshStandardMaterial,
  } from "svelthree";
  import type { Scene } from "svelthree-three";
  import { TABLE_WIDTH, HAND_TO_TABLE_EDGE, WALL_TILT } from "./constants";

  import { DrawTileAction } from "../game-state/actions";

  import PlayerSide from "./PlayerSide.svelte";
  import DiscardPile from "./DiscardPile.svelte";
  import Walls from "./Walls.svelte";
  import Group from "../svelthree-patch/Group.svelte";
  import { PlayerControlledPhase } from "../game-state/phases";
  import CenterTurnIndicator from "./turn-indicator/CenterTurnIndicator.svelte";
  import { StandardMahjong } from "../tiles";

  export let hand: Hand;
  export let scene: Scene;
  export let onUpdate: () => void;

  const geometry = new PlaneBufferGeometry(TABLE_WIDTH, TABLE_WIDTH, 1);
  const material = new MeshStandardMaterial({ color: 0x005100 });
  $: currentHand = hand;
  $: currentPhase = currentHand.getCurrentPhase();
  $: discardPile = currentHand.discardPile;
  $: wallStacks = currentHand.physicalWall.wallStacks;
</script>

<Group {scene} let:parent>
  <Mesh
    {scene}
    {geometry}
    {material}
    pos={[0, 0, -0.01]}
    receiveShadow
    mat={{ roughness: 1, metalness: 0, side: DoubleSide }}
  />
  {#if !(currentPhase instanceof PlayerControlledPhase)}
    <CenterTurnIndicator
      {scene}
      {parent}
      pos={[0, 0, 0.01]}
      rot={[0, 0, WALL_TILT]}
    />
  {/if}
  <Walls
    {scene}
    {wallStacks}
    onClick={() => {
      currentHand.tryExecuteAction(new DrawTileAction(currentHand.players[0]));
      onUpdate();
    }}
  />
  <DiscardPile {scene} tiles={discardPile} rot={[0, 0, WALL_TILT]} />
  {#each currentHand.players as player, index}
    <PlayerSide
      {scene}
      {player}
      {parent}
      phase={currentPhase}
      showControls={player.wind === StandardMahjong.SUIT_EAST}
      hasTurnControl={currentPhase instanceof PlayerControlledPhase &&
        currentPhase.player === player}
      playerUi={currentHand}
      pos={new Vector3(0, -TABLE_WIDTH / 2 + HAND_TO_TABLE_EDGE, 0)
        .applyAxisAngle(new Vector3(0, 0, 1), (index * Math.PI) / 2)
        .toArray()}
      rot={[0, 0, (index * Math.PI) / 2]}
      onUpdate={() => {
        hand = hand;
        onUpdate();
      }}
    />
  {/each}
</Group>

// src/scene/Table.tsx
import type { Hand } from "../game-state/game-state";
import {
  DoubleSide,
  PlaneBufferGeometry,
  Vector3,
  MeshStandardMaterial,
} from "three";
import { TABLE_WIDTH, HAND_TO_TABLE_EDGE, WALL_TILT } from "./constants";

import { DrawTileAction } from "../game-state/actions";
import { useContext } from "react";
import { HandPhase, PlayerControlledPhase } from "../game-state/phases";
import { StandardMahjong } from "../tiles";
import CenterTurnIndicator from "./turn-indicator/CenterTurnIndicator";
import Walls from "./Walls";
import DiscardPile from "./DiscardPile";
import PlayerSide from "./PlayerSide";
import { GameContext } from "../GameContext";
// import DiscardPile from "./DiscardPile.svelte";
// import Walls from "./Walls.svelte";
// import Group from "../svelthree-patch/Group.svelte";
// import { PlayerControlledPhase } from "../game-state/phases";
// import CenterTurnIndicator from "./turn-indicator/CenterTurnIndicator.svelte";
// import { StandardMahjong } from "../tiles";

export type TableProps = {
  hand: Hand;
  phase: HandPhase;
};

const Table = ({ hand, phase }: TableProps) => {
  const gameContext = useContext(GameContext);
  const onUpdate = gameContext.update;

  const geometry = new PlaneBufferGeometry(TABLE_WIDTH, TABLE_WIDTH, 1);
  const material = new MeshStandardMaterial({
    color: 0x005100,
    roughness: 1,
    metalness: 0,
    side: DoubleSide,
  });

  const discardPile = hand.discardPile;
  const wallStacks = hand.physicalWall.wallStacks;

  return (
    <group>
      <mesh
        material={material}
        geometry={geometry}
        position={[0, 0, -0.01]}
        receiveShadow
      />
      {!(phase instanceof PlayerControlledPhase) && (
        <CenterTurnIndicator
          position={[0, 0, 0.01]}
          rotation={[0, 0, WALL_TILT]}
        />
      )}
      <Walls
        wallStacks={wallStacks}
        onClick={() => {
          hand.tryExecuteAction(new DrawTileAction(hand.players[0]));
          onUpdate();
        }}
      />
      <DiscardPile tiles={discardPile} rotation={[0, 0, WALL_TILT]} />
      {hand.players.map((player, index) => {
        return (
          <PlayerSide
            key={index}
            player={player}
            phase={phase}
            showControls={player.wind === StandardMahjong.SUIT_EAST}
            hasTurnControl={
              phase instanceof PlayerControlledPhase && phase.player === player
            }
            playerUi={hand}
            position={new Vector3(0, -TABLE_WIDTH / 2 + HAND_TO_TABLE_EDGE, 0)
              .applyAxisAngle(new Vector3(0, 0, 1), (index * Math.PI) / 2)
              .toArray()}
            rotation={[0, 0, (index * Math.PI) / 2]}
          />
        );
      })}
    </group>
  );
};

export default Table;
