// src/scene/TooltipContext.svelte
<script lang="ts">
  import { setContext } from "svelte";

  import { KEY_TOOLTIP_CONTEXT } from "./constants";

  let tooltipContainer: HTMLElement;

  const getTooltipStyle = (pageX: number, pageY: number): string => {
    return `transform: translate(0%, -100%) translate(${pageX}px, ${pageY}px)`;
  };

  let tooltipStyle = getTooltipStyle(0, 0);

  const updateLocation = (event: MouseEvent) => {
    tooltipStyle = getTooltipStyle(event.pageX, event.pageY);
  };

  export const setContent = (newTooltipContent: HTMLElement) => {
    tooltipContainer.replaceChildren(newTooltipContent);
  };

  setContext(KEY_TOOLTIP_CONTEXT, {
    setContent: setContent,
  });
</script>

<div class="tooltip" style={tooltipStyle} bind:this={tooltipContainer} />
<slot />
<svelte:window on:mousemove={updateLocation} />

<style>
  .tooltip {
    position: absolute;
    pointer-events: none;
    left: 0;
    top: 0;
  }
</style>

// src/scene/TooltipContext.tsx
import {
  PropsWithChildren,
  useEffect,
  createContext,
  useState,
  useRef,
  useMemo,
} from "react";

import "./TooltipContext.css";

export type TooltipContextValue = {
  setContent: (content: string | null) => void;
};

export const TooltipContext: React.Context<TooltipContextValue> = createContext(
  {
    setContent: (content: string | null) => {},
  }
);

const TooltipContextProvider = (props: PropsWithChildren<{}>) => {
  const tooltipContainer = useRef(null);

  const [content, setContent] = useState<string | null>(null);

  const getTooltipStyle = (
    pageX: number,
    pageY: number
  ): React.CSSProperties => {
    return {
      transform: `translate(0%, -100%) translate(${pageX}px, ${pageY}px)`,
    };
  };

  const [tooltipStyle, setTooltipStyle] = useState(getTooltipStyle(0, 0));

  useEffect(() => {
    const updateLocation = (event: MouseEvent) => {
      setTooltipStyle(getTooltipStyle(event.pageX, event.pageY));
    };
    window.addEventListener("mousemove", updateLocation);
  }, []);

  const value = useMemo(
    () => ({
      setContent,
    }),
    [setContent]
  );

  return (
    <TooltipContext.Provider value={value}>
      {props.children}
      {content && (
        <div
          className="tooltip-container"
          style={tooltipStyle}
          ref={tooltipContainer}
        >
          <div className="tooltip">{content}</div>
        </div>
      )}
    </TooltipContext.Provider>
  );
};

export default TooltipContextProvider;
