// src/scene/turn-indicator/CenterTurnIndicator.svelte
<script lang="ts">
  import { PlaneBufferGeometry, MeshStandardMaterial } from "svelthree";
  import type { Scene } from "svelthree-three";
  import Mesh from "svelthree/src/components/Mesh.svelte";
  import { CENTER_SQUARE_LENGTH } from "../constants";
  import { animateMaterial } from "./anim";

  export let scene: Scene;

  const geometry = new PlaneBufferGeometry(
    CENTER_SQUARE_LENGTH,
    CENTER_SQUARE_LENGTH
  );
  const material = new MeshStandardMaterial({
    color: 0xffffff,
    transparent: true,
  });
  animateMaterial(material);
</script>

<Mesh {scene} {geometry} {material} {...$$restProps} />

// src/scene/turn-indicator/CenterTurnIndicator.tsx
import { MeshProps } from "react-three-fiber";
import { PlaneBufferGeometry, MeshStandardMaterial } from "three";
import { CENTER_SQUARE_LENGTH } from "../constants";
import { WithoutGeoMat } from "../object-props";
import { animateMaterial } from "./anim";

const CenterTurnIndicator = (props: WithoutGeoMat<MeshProps>) => {
  const geometry = new PlaneBufferGeometry(
    CENTER_SQUARE_LENGTH,
    CENTER_SQUARE_LENGTH
  );
  const material = new MeshStandardMaterial({
    color: 0xffffff,
    transparent: true,
  });
  animateMaterial(material);

  return <mesh geometry={geometry} material={material} {...props} />;
};

export default CenterTurnIndicator;
