// src/scene/turn-indicator/PlayerTurnIndicator.svelte
<script lang="ts">
  import { PlaneBufferGeometry, MeshStandardMaterial } from "svelthree";
  import type { Scene } from "svelthree-three";
  import Mesh from "svelthree/src/components/Mesh.svelte";
  import { TURN_INDICATOR_HEIGHT, TURN_INDICATOR_WIDTH } from "../constants";
  import { animateMaterial } from "./anim";

  export let scene: Scene;

  const geometry = new PlaneBufferGeometry(
    TURN_INDICATOR_WIDTH,
    TURN_INDICATOR_HEIGHT
  );
  const material = new MeshStandardMaterial({
    color: 0xffffff,
    transparent: true,
  });
  animateMaterial(material);
</script>

<Mesh {scene} {geometry} {material} {...$$restProps} />

// src/scene/turn-indicator/PlayerTurnIndicator.tsx
import { MeshProps } from 'react-three-fiber';
import { PlaneBufferGeometry, MeshStandardMaterial } from 'three';
import { TURN_INDICATOR_HEIGHT, TURN_INDICATOR_WIDTH } from '../constants';
import { WithoutGeoMat } from '../object-props';
import { animateMaterial } from './anim';

const PlayerTurnIndicator = (props: WithoutGeoMat<MeshProps>) => {
  const geometry = new PlaneBufferGeometry(
    TURN_INDICATOR_WIDTH,
    TURN_INDICATOR_HEIGHT
  );
  const material = new MeshStandardMaterial({
    color: 0xffffff,
    transparent: true,
  });
  animateMaterial(material);

  return <mesh geometry={geometry} material={material} {...props} />;
};

export default PlayerTurnIndicator;
